---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: byfn-pv
  namespace: byfn
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/www/byfn-on-k8s/
    server: 192.168.126.128

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: byfn
 name: byfn-pvc
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Gi

