---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: byfn
  name:	peer1-org2
spec:
  selector:
    matchLabels:
        peer-id: peer1.org2.example.com
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        peer-id: peer1.org2.example.com
    spec:
        containers:
        - name: peer1-org2
          image: hyperledger/fabric-peer:1.4.2
          imagePullPolicy: Never
          ports:
            - containerPort: 30041
            - containerPort: 30042
          resources:
            limits:
              cpu: "0.125"
              memory: "128Mi"
          env:
           - name: CORE_PEER_ADDRESSAUTODETECT
             value: "true"
           - name: CORE_VM_ENDPOINT
             value: "unix:///host/var/run/docker.sock"
           - name: FABRIC_LOGGING_SPEC
             value: "INFO"
           - name: CORE_PEER_TLS_ENABLED
             value: "true"
           - name: CORE_PEER_GOSSIP_USELEADERELECTION
             value: "true"
           - name: CORE_PEER_GOSSIP_ORGLEADER
             value: "false"
           - name: CORE_PEER_PROFILE_ENABLED
             value: "true"
           - name: CORE_PEER_TLS_CERT_FILE
             value: "/etc/hyperledger/fabric/tls/server.crt"
           - name: CORE_PEER_TLS_KEY_FILE
             value: "/etc/hyperledger/fabric/tls/server.key"
           - name: CORE_PEER_TLS_ROOTCERT_FILE
             value: "/etc/hyperledger/fabric/tls/ca.crt"
           - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
             value: "false"
           - name: CORE_PEER_ID
             value: "peer1.org2.example.com"
           - name: CORE_PEER_ADDRESS
             value: "peer1.org2.example.com:30041"
           - name: CORE_PEER_LISTENADDRESS
             value: 0.0.0.0:30041  
           - name: CORE_PEER_CHAINCODEADDRESS
             value: "peer1.org2.example.com:30042"  
           - name: CORE_PEER_CHAINCODELISTENADDRESS
             value: 0.0.0.0:30042  
           - name: CORE_PEER_GOSSIP_BOOTSTRAP
             value: "peer1.org2.example.com:30041"
           - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
             value: "peer1.org2.example.com:30041"
           - name: CORE_PEER_LOCALMSPID
             value: "Org2MSP"
           - name: ORDERER_URL
             value: orderer:7050  
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer 
          command: ["peer"]
          args: ["node","start"]
          volumeMounts:
           - mountPath: /etc/hyperledger/fabric/msp
             name: byfn-pv
             subPath: crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp
           - mountPath: /etc/hyperledger/fabric/tls
             name: byfn-pv
             subPath: crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls
           - mountPath: /etc/hyperledger/fabric/users
             name: byfn-pv
             subPath: crypto-config/peerOrganizations/org2.example.com/users
           - mountPath: /var/hyperledger/production
             name: byfn-pv
             subPath: data/peer1.org2.example.com
           - mountPath: /host/var/run
             name: run
        volumes:
         - name: byfn-pv
           persistentVolumeClaim:
               claimName: byfn-pvc
         - name: run
           hostPath:
             path: /var/run

---
apiVersion: v1
kind: Service
metadata:
   namespace: byfn
   name: peer1-org2-service
spec:
 selector:
   peer-id: peer1.org2.example.com
 type: NodePort
 ports:
    - port: 30041
      targetPort: 30041  
      nodePort: 30041  
      name: endpoint          
    - port: 30042
      targetPort: 30042
      nodePort: 30042
      name: chaincode         


